"""Add AssessmentResetRequestTable

Revision ID: b7568f2449a4
Revises: 7dfe24ee7aca
Create Date: 2026-04-30 12:00:27.932708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7568f2449a4'
down_revision: Union[str, Sequence[str], None] = '7dfe24ee7aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_reset_request_table',
    sa.Column('Request_ID', sa.String(length=50), nullable=False),
    sa.Column('User_ID', sa.String(length=50), nullable=False),
    sa.Column('Assessment_ID', sa.String(length=50), nullable=False),
    sa.Column('Reason', sa.String(length=500), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('Requested_At', sa.DateTime(), nullable=False),
    sa.Column('Resolved_At', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Assessment_ID'], ['course_assessment_table.Assessment_ID'], ),
    sa.ForeignKeyConstraint(['User_ID'], ['user_profile.user_id'], ),
    sa.PrimaryKeyConstraint('Request_ID')
    )
    op.drop_table('assessment_answer_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_answer_table',
    sa.Column('Answer_ID', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Attempt_ID', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Question_ID', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Option_ID', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Is_Correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Attempt_ID'], ['assessment_attempt_table.Attempt_ID'], name=op.f('assessment_answer_table_Attempt_ID_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Option_ID'], ['question_option_table.Option_ID'], name=op.f('assessment_answer_table_Option_ID_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Question_ID'], ['course_question_table.Question_ID'], name=op.f('assessment_answer_table_Question_ID_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Answer_ID', name=op.f('assessment_answer_table_pkey'))
    )
    op.drop_table('assessment_reset_request_table')
    # ### end Alembic commands ###
