"""Add AssessmentAnswerTable back

Revision ID: f16f841cc614
Revises: b7568f2449a4
Create Date: 2026-04-30 12:01:30.649764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16f841cc614'
down_revision: Union[str, Sequence[str], None] = 'b7568f2449a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_answer_table',
    sa.Column('Answer_ID', sa.String(length=50), nullable=False),
    sa.Column('Attempt_ID', sa.String(length=50), nullable=False),
    sa.Column('Question_ID', sa.String(length=50), nullable=False),
    sa.Column('Option_ID', sa.String(length=50), nullable=False),
    sa.Column('Is_Correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Attempt_ID'], ['assessment_attempt_table.Attempt_ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Option_ID'], ['question_option_table.Option_ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Question_ID'], ['course_question_table.Question_ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Answer_ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_answer_table')
    # ### end Alembic commands ###
