"""add degree table and user_degree

Revision ID: fcdf639aebc6
Revises: f16f841cc614
Create Date: 2026-07-30 16:07:06.521108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcdf639aebc6'
down_revision: Union[str, Sequence[str], None] = 'f16f841cc614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('degree_table',
    sa.Column('degree_id', sa.String(), nullable=False),
    sa.Column('degree_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('degree_id')
    )
    op.alter_column('course_table', 'thumbnail',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('user_profile', sa.Column('user_degree', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'user_degree')
    op.alter_column('course_table', 'thumbnail',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.drop_table('degree_table')
    # ### end Alembic commands ###
